### ISSUE TITLE
How to get data from Array

### ISSUE THREAD

**Issue by FranciscoJavierPRamos** [rapidpro/expressions#26]
Example: `contact.put("groups", Arrays.asList("Testers", "Developers"));`
I getting an error: `context.resolveVariable("contact.groups.something");`

Help me please!

**Comment by rowanseymour** [comment]
@FranciscoJavierPRamos could you provide some more information about what you're trying to do.

**Comment by FranciscoJavierPRamos** [comment]
I have this code:
`


        Map<String, Object> contact = new HashMap<>();
        contact.put("*", "Bob");
        contact.put("name", "Bob");
        contact.put("age", 33);
        contact.put("join_date_1", "28-08-2015 13:06");
        contact.put("isnull", null);
        contact.put("isbool", true);
        contact.put("isfloat", 1.5f);
        contact.put("islong", 9223372036854775807L);
        contact.put("isdict", dict);

        Map<String, Object> address1 = new HashMap<>();
        address1.put("country", "México");
        address1.put("city", "Puebla");

        Map<String, Object> address2 = new HashMap<>();
        address2.put("country", "España");
        address2.put("city", "Barcelona");

        contact.put("address", Arrays.asList(address1, address2));
`

Im trying to get data some like this: `contact.address[0].country`

**Comment by rowanseymour** [comment]
Ah ok. This expressions library doesn't support array indexing. However we're in the process of developing a new engine which will: https://github.com/nyaruka/goflow

**Comment by FranciscoJavierPRamos** [comment]
Thank you!

**Comment by rowanseymour** [comment]
Sorry @nicpottier just reminded me you should be able to do `contact.address.0.country`! 

In the new goflow engine you'll be able to write `[0]`

**Comment by FranciscoJavierPRamos** [comment]
`contact.address.0.country` does not work for me :(
