### ISSUE TITLE
How to truncate number with decimals?

### ISSUE THREAD

**Issue by javierpe** [rapidpro/expressions#29]
21.599999999999998 to 21.59

**Comment by rowanseymour** [comment]
Take a look at the `FIXED` function https://github.com/rapidpro/expressions/blob/master/python/temba_expressions/functions/excel.py#L50

**Comment by javierpe** [comment]
These function gets 21.6

**Comment by rowanseymour** [comment]
It has a second parameter which is the number of decimal places, e.g. `@(FIXED("21.59999", 2))`. It will round to 2 decimal places so you'll get `21.60`

If you want to only round down, try `@(ROUNDDOWN("21.59999", 2))`
