### ISSUE TITLE
Add function that always return an empty string so it can be used to clear field values

### ISSUE THREAD

**Issue by norkans7** [rapidpro/expressions#33]

**Comment by rowanseymour** [comment]
The problem isn't the expression engine, it's the old editor. In the engine it's perfectly valid to set a field value to empty string. It's the old editor which doesn't accept that input being empty so we've ended up telling people to use `@("")`.

The new editor addresses this and I think we just keep using the `@("")` workaround until then - which the legacy->new flow migration will replace with empty string.

**Comment by nicpottier** [comment]
Do we actually detect `@("")` as a special case expression and replace with `""` in new flows? (not saying at evaluation time, saying in the definition itself?

**Comment by rowanseymour** [comment]
it's at flow migration time  https://github.com/nyaruka/goflow/blob/master/legacy/expressions/migrate.go#L73

so a `set_contact_field` action that was `"value": "@(\"\")"` becomes `"value": ""`

**Comment by nicpottier** [comment]
noice!
